# Regenerates the test data headers of test_metal_lisa.mm from GeoDa's sample
# datasets. Run from the repository root: Rscript Algorithms/make_test_data.R
# The standalone test can't read samples.sqlite itself: queen contiguity weights
# need a geometry engine, so variables and weights are dumped to plain C arrays.
suppressMessages(library(sf))

samples <- "BuildTools/CommonDistFiles/web_plugins/samples.sqlite"

dump <- function(layer, variable, prefix, links) {
  g <- st_read(samples, layer, quiet = TRUE)
  x <- st_drop_geometry(g)
  x <- x[[which(tolower(names(x)) == variable)]]
  stopifnot(is.numeric(x), length(x) == nrow(g), !anyNA(x))
  nb <- st_intersects(g, g) # queen contiguity
  nb <- lapply(seq_along(nb), function(i) setdiff(nb[[i]], i))
  card <- lengths(nb)
  stopifnot(sum(card) == links) # same as GeoDa's queen weights
  arr <- function(v) paste(strwrap(paste(v, collapse = ", "), 100, prefix = "    "), collapse = "\n")
  guard <- sprintf("__GEODA_CENTER_TEST_DATA_%s_H__", toupper(prefix))
  writeLines(c(
    sprintf("// \"%s\" %s with queen contiguity weights: %d obs, %d links, %d isolates.",
            layer, variable, nrow(g), links, sum(card == 0)),
    sprintf("// Generated by Algorithms/make_test_data.R from %s", samples),
    sprintf("#ifndef %s\n#define %s\n", guard, guard),
    sprintf("static const int %s_n = %d;", prefix, nrow(g)),
    sprintf("static const double %s_x[%d] = {\n%s\n};", prefix, nrow(g), arr(x)),
    sprintf("static const int %s_nbr_offset[%d] = {\n%s\n};", prefix, nrow(g) + 1, arr(c(0, cumsum(card)))),
    sprintf("static const int %s_nbrs[%d] = {\n%s\n};", prefix, links, arr(unlist(nb) - 1)),
    "\n#endif"), sprintf("Algorithms/test_data_%s.h", prefix))
}

dump("Guerry", "donatns", "guerry", 420)
dump("US Homicides", "hr90", "natregimes", 18168)
